/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SectorPanel.java
 *
 * Created on Jan 2, 2010, 3:50:38 AM
 */

package com.kitfox.volume.mask;

import static com.kitfox.volume.mask.SectorMask.Q000;
import static com.kitfox.volume.mask.SectorMask.Q001;
import static com.kitfox.volume.mask.SectorMask.Q010;
import static com.kitfox.volume.mask.SectorMask.Q011;
import static com.kitfox.volume.mask.SectorMask.Q100;
import static com.kitfox.volume.mask.SectorMask.Q101;
import static com.kitfox.volume.mask.SectorMask.Q110;
import static com.kitfox.volume.mask.SectorMask.Q111;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import javax.swing.JSlider;
import javax.vecmath.Vector3f;

import com.kitfox.volume.viewer.ViewerCube;

/**
 *
 * @author kitfox
 */
public class SectorPanel extends javax.swing.JPanel
        implements PropertyChangeListener
{
    private static final long serialVersionUID = 0;

    protected ViewerCube cube;
    public static final String PROP_CUBE = "cube";


    /** Creates new form SectorPanel */
    public SectorPanel()
    {
        initComponents();
    }

    public void propertyChange(PropertyChangeEvent evt)
    {
        updateFromCube();
    }

    private void updateFromCube()
    {
        SectorMask mask = cube.getOctantMask();
        Vector3f center = mask.getCenter();
        setSliderValue(slider_centerX, center.x);
        setSliderValue(slider_centerY, center.y);
        setSliderValue(slider_centerZ, center.z);

        int m = mask.getMask();
        check_q000.setSelected((m & Q000) != 0);
        check_q001.setSelected((m & Q001) != 0);
        check_q010.setSelected((m & Q010) != 0);
        check_q011.setSelected((m & Q011) != 0);
        check_q100.setSelected((m & Q100) != 0);
        check_q101.setSelected((m & Q101) != 0);
        check_q110.setSelected((m & Q110) != 0);
        check_q111.setSelected((m & Q111) != 0);

    }

    private void setSliderValue(JSlider slider, float value)
    {
        int max = slider.getMaximum();
        int min = slider.getMinimum();
        int val = (int)(min + value * (max - min));
        slider.setValue(val);
    }

    private float normalValue(JSlider slider)
    {
        int val = slider.getValue();
        int min = slider.getMinimum();
        int max = slider.getMaximum();

        return (float)(val - min) / (max - min);
    }

    private void updateCenter()
    {
        if (cube == null)
        {
            return;
        }

        float x = normalValue(slider_centerX);
        float y = normalValue(slider_centerY);
        float z = normalValue(slider_centerZ);
        SectorMask mask = cube.getOctantMask();
        mask.setCenter(new Vector3f(x, y, z));
    }

    private void updateMask()
    {
        if (cube == null)
        {
            return;
        }

        int val = 0;
        if (check_q000.isSelected()) { val |= Q000; }
        if (check_q100.isSelected()) { val |= Q100; }
        if (check_q010.isSelected()) { val |= Q010; }
        if (check_q110.isSelected()) { val |= Q110; }
        if (check_q001.isSelected()) { val |= Q001; }
        if (check_q101.isSelected()) { val |= Q101; }
        if (check_q011.isSelected()) { val |= Q011; }
        if (check_q111.isSelected()) { val |= Q111; }

        SectorMask mask = cube.getOctantMask();
        mask.setMask(val);
    }

    private void setSelection(int mask)
    {
        check_q111.setSelected((mask & Q111) != 0);
        check_q011.setSelected((mask & Q011) != 0);
        check_q101.setSelected((mask & Q101) != 0);
        check_q001.setSelected((mask & Q001) != 0);
        check_q110.setSelected((mask & Q110) != 0);
        check_q010.setSelected((mask & Q010) != 0);
        check_q100.setSelected((mask & Q100) != 0);
        check_q000.setSelected((mask & Q000) != 0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        slider_centerX = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        slider_centerY = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        slider_centerZ = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        check_q111 = new javax.swing.JCheckBox();
        check_q011 = new javax.swing.JCheckBox();
        check_q010 = new javax.swing.JCheckBox();
        check_q110 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        check_q101 = new javax.swing.JCheckBox();
        check_q000 = new javax.swing.JCheckBox();
        check_q001 = new javax.swing.JCheckBox();
        check_q100 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        bn_all = new javax.swing.JButton();
        bn_none = new javax.swing.JButton();
        bn_x0 = new javax.swing.JButton();
        bn_x1 = new javax.swing.JButton();
        bn_y0 = new javax.swing.JButton();
        bn_y1 = new javax.swing.JButton();
        bn_z0 = new javax.swing.JButton();
        bn_z1 = new javax.swing.JButton();

        jLabel1.setText("Center X");

        slider_centerX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_centerXStateChanged(evt);
            }
        });

        jLabel2.setText("Center Y");

        slider_centerY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_centerYStateChanged(evt);
            }
        });

        jLabel3.setText("Center Z");

        slider_centerZ.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_centerZStateChanged(evt);
            }
        });

        check_q111.setSelected(true);
        check_q111.setText("+X +Y +Z");
        check_q111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q111ActionPerformed(evt);
            }
        });

        check_q011.setSelected(true);
        check_q011.setText("-X +Y +Z");
        check_q011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q011ActionPerformed(evt);
            }
        });

        check_q010.setSelected(true);
        check_q010.setText("-X +Y -Z");
        check_q010.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q010ActionPerformed(evt);
            }
        });

        check_q110.setSelected(true);
        check_q110.setText("+X +Y -Z");
        check_q110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q110ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_q011)
                    .addComponent(check_q010))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_q111)
                    .addComponent(check_q110))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_q111)
                    .addComponent(check_q011))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_q110)
                    .addComponent(check_q010))
                .addContainerGap())
        );

        check_q101.setSelected(true);
        check_q101.setText("+X -Y +Z");
        check_q101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q101ActionPerformed(evt);
            }
        });

        check_q000.setSelected(true);
        check_q000.setText("-X -Y -Z");
        check_q000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q000ActionPerformed(evt);
            }
        });

        check_q001.setSelected(true);
        check_q001.setText("-X -Y +Z");
        check_q001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q001ActionPerformed(evt);
            }
        });

        check_q100.setSelected(true);
        check_q100.setText("+X -Y -Z");
        check_q100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_q100ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_q000)
                    .addComponent(check_q001))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_q101)
                    .addComponent(check_q100))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_q001)
                    .addComponent(check_q101))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_q000)
                    .addComponent(check_q100))
                .addContainerGap())
        );

        bn_all.setText("All");
        bn_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_allActionPerformed(evt);
            }
        });

        bn_none.setText("None");
        bn_none.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_noneActionPerformed(evt);
            }
        });

        bn_x0.setText("-X");
        bn_x0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_x0ActionPerformed(evt);
            }
        });

        bn_x1.setText("+X");
        bn_x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_x1ActionPerformed(evt);
            }
        });

        bn_y0.setText("-Y");
        bn_y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_y0ActionPerformed(evt);
            }
        });

        bn_y1.setText("+Y");
        bn_y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_y1ActionPerformed(evt);
            }
        });

        bn_z0.setText("-Z");
        bn_z0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_z0ActionPerformed(evt);
            }
        });

        bn_z1.setText("+Z");
        bn_z1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_z1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(bn_all)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bn_none))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(bn_x0)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bn_x1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(bn_y0)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bn_y1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(bn_z0)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bn_z1)))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bn_all)
                        .addComponent(bn_none))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bn_x0)
                        .addComponent(bn_x1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bn_y0)
                        .addComponent(bn_y1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bn_z0)
                        .addComponent(bn_z1))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slider_centerX, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(slider_centerY, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slider_centerZ, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_centerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(slider_centerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(slider_centerZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void slider_centerXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_centerXStateChanged
        updateCenter();
    }//GEN-LAST:event_slider_centerXStateChanged

    private void slider_centerYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_centerYStateChanged
        updateCenter();
    }//GEN-LAST:event_slider_centerYStateChanged

    private void slider_centerZStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_centerZStateChanged
        updateCenter();
    }//GEN-LAST:event_slider_centerZStateChanged

    private void check_q011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q011ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q011ActionPerformed

    private void check_q111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q111ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q111ActionPerformed

    private void check_q010ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q010ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q010ActionPerformed

    private void check_q110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q110ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q110ActionPerformed

    private void check_q001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q001ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q001ActionPerformed

    private void check_q101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q101ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q101ActionPerformed

    private void check_q000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q000ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q000ActionPerformed

    private void check_q100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_q100ActionPerformed
        updateMask();
    }//GEN-LAST:event_check_q100ActionPerformed

    private void bn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_allActionPerformed
        setSelection(0xff);
        updateMask();
    }//GEN-LAST:event_bn_allActionPerformed

    private void bn_noneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_noneActionPerformed
        setSelection(0);
        updateMask();
    }//GEN-LAST:event_bn_noneActionPerformed

    private void bn_x0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_x0ActionPerformed
        setSelection(Q000 | Q001 | Q010 | Q011);
        updateMask();
    }//GEN-LAST:event_bn_x0ActionPerformed

    private void bn_x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_x1ActionPerformed
        setSelection(Q100 | Q101 | Q110 | Q111);
        updateMask();
    }//GEN-LAST:event_bn_x1ActionPerformed

    private void bn_y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_y0ActionPerformed
        setSelection(Q000 | Q001 | Q100 | Q101);
        updateMask();
    }//GEN-LAST:event_bn_y0ActionPerformed

    private void bn_y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_y1ActionPerformed
        setSelection(Q010 | Q011 | Q110 | Q111);
        updateMask();
    }//GEN-LAST:event_bn_y1ActionPerformed

    private void bn_z0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_z0ActionPerformed
        setSelection(Q000 | Q100 | Q010 | Q110);
        updateMask();
    }//GEN-LAST:event_bn_z0ActionPerformed

    private void bn_z1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_z1ActionPerformed
        setSelection(Q001 | Q101 | Q011 | Q111);
        updateMask();
    }//GEN-LAST:event_bn_z1ActionPerformed


    /**
     * Get the value of cube
     *
     * @return the value of cube
     */
    public ViewerCube getCube()
    {
        return cube;
    }

    /**
     * Set the value of cube
     *
     * @param cube new value of cube
     */
    public void setCube(ViewerCube cube)
    {
        ViewerCube oldCube = this.cube;
        if (this.cube != null)
        {
            this.cube.getOctantMask().removePropertyChangeListener(this);
        }
        this.cube = cube;
        if (this.cube != null)
        {
            this.cube.getOctantMask().addPropertyChangeListener(this);
        }
        updateFromCube();
        firePropertyChange(PROP_CUBE, oldCube, cube);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_all;
    private javax.swing.JButton bn_none;
    private javax.swing.JButton bn_x0;
    private javax.swing.JButton bn_x1;
    private javax.swing.JButton bn_y0;
    private javax.swing.JButton bn_y1;
    private javax.swing.JButton bn_z0;
    private javax.swing.JButton bn_z1;
    private javax.swing.JCheckBox check_q000;
    private javax.swing.JCheckBox check_q001;
    private javax.swing.JCheckBox check_q010;
    private javax.swing.JCheckBox check_q011;
    private javax.swing.JCheckBox check_q100;
    private javax.swing.JCheckBox check_q101;
    private javax.swing.JCheckBox check_q110;
    private javax.swing.JCheckBox check_q111;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider slider_centerX;
    private javax.swing.JSlider slider_centerY;
    private javax.swing.JSlider slider_centerZ;
    // End of variables declaration//GEN-END:variables

}
